packages:
  - name: media
    functions:
      - name: compress
        runtime: nodejs:18
        web: true
        limits:
          timeout: 900000     # 15 minutes max
          memory: 1024        # 1 GB max
        environment:
          PROD_SPACES_ENDPOINT: "${PROD_SPACES_ENDPOINT}"
          PROD_SPACES_KEY: "${PROD_SPACES_KEY}"
          PROD_SPACES_SECRET: "${PROD_SPACES_SECRET}"
          PROD_SPACES_BUCKET: "${PROD_SPACES_BUCKET}"
          PROD_GRAPHQL_ENDPOINT: "${PROD_GRAPHQL_ENDPOINT}"
          STAGGING_SPACES_ENDPOINT: "${STAGGING_SPACES_ENDPOINT}"
          STAGGING_SPACES_KEY: "${STAGGING_SPACES_KEY}"
          STAGGING_SPACES_SECRET: "${STAGGING_SPACES_SECRET}"
          STAGGING_SPACES_BUCKET: "${STAGGING_SPACES_BUCKET}"
          STAGGING_GRAPHQL_ENDPOINT: "${STAGGING_GRAPHQL_ENDPOINT}"
  - name: documents
    functions:
      - name: compress
        runtime: nodejs:18
        web: true
        limits:
          timeout: 900000     # 15 minutes max
          memory: 1024        # 1 GB max
        environment:
          PROD_SPACES_ENDPOINT: "${PROD_SPACES_ENDPOINT}"
          PROD_SPACES_KEY: "${PROD_SPACES_KEY}"
          PROD_SPACES_SECRET: "${PROD_SPACES_SECRET}"
          PROD_SPACES_BUCKET: "${PROD_SPACES_BUCKET}"
          PROD_GRAPHQL_ENDPOINT: "${PROD_GRAPHQL_ENDPOINT}"
          STAGGING_SPACES_ENDPOINT: "${STAGGING_SPACES_ENDPOINT}"
          STAGGING_SPACES_KEY: "${STAGGING_SPACES_KEY}"
          STAGGING_SPACES_SECRET: "${STAGGING_SPACES_SECRET}"
          STAGGING_SPACES_BUCKET: "${STAGGING_SPACES_BUCKET}"
          STAGGING_GRAPHQL_ENDPOINT: "${STAGGING_GRAPHQL_ENDPOINT}"